version: '3.8'

services:
  # Kong Gateway
  kong:
    build:
      context: ./services/kong
      dockerfile: Dockerfile
    container_name: kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002
      - KONG_LOG_LEVEL=debug
    ports:
      - "8000:8000"     
      - "8001:8001"   
      - "8002:8002"
    depends_on:
      - user_service
      - business_service
      - payment_service
    networks:
      - microservices_network

  # User Service
  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8003:8000"
    volumes:
      - ${PWD}/services/user_service/app/static:/app/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    networks:
      - microservices_network

  business_service:
    build:
      context: ./services/business_service
      dockerfile: Dockerfile
    container_name: business_service
    ports:
      - "8004:8000"
    volumes:
      - ${PWD}/services/business_service/app/static:/app/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    networks:
      - microservices_network

  # Payment Service
  payment_service:
    build:
      context: ./services/payment_service
      dockerfile: Dockerfile
    container_name: payment_service
    ports:
      - "8005:8000"
    volumes:
      - ${PWD}/services/payment_service/app/static:/app/app/static
    environment:
      - BUSINESS_SERVICE_URL=http://business_service:8000
      - MOMO_RETURN_URL=http://localhost:8000/api/payment/momo/result
      - MOMO_NOTIFY_URL=http://localhost:8000/api/payment/momo/ipn
    networks:
      - microservices_network

  # Django Client - CHẠY RIÊNG BIỆT, GỌI API QUA HOST
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: django_client
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://host.docker.internal:8000
      - DJANGO_DEBUG=True
      - PYTHONUNBUFFERED=1  # Để xem logs real-time
    command: >
      sh -c "echo 'Starting Django server...' &&
            python manage.py migrate &&
            echo 'Migrations completed' &&
            echo 'Starting server on 0.0.0.0:3000' &&
            python manage.py runserver 0.0.0.0:3000 --verbosity=2"
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  microservices_network:
    driver: bridge